### ISSUE TITLE
Was genau ist mit "TZ environment variable" gemeint?

### ISSUE THREAD

**Issue by reneoelke** [reneoelke/Php53to54#1]
In der Rubrik "Backward Incompatible Changes" (http://www.php.net/manual/en/migration54.incompatible.php) heißt es u.a.

> In the date and time extension, the timezone can no longer be set using the TZ environment variable. Instead you have to specify a timezone using the date.timezone php.ini option or date_default_timezone_set() function. PHP will no longer attempt to guess the timezone, and will instead fall back to "UTC" and issue a E_WARNING."

Es sollte herausgefunden werden, was genau mit "TZ environment variable" gemeint ist. Wird eine spezielle Methode dafür verwendet oder setenv() mit einem definierten Parameter? Anhand dessen kann man dann den Code prüfen und entsprechend darauf hinweisen.

**Comment by Ephigenia** [comment]
[TZ Environment Variable](http://docstore.mik.ua/orelly/unix/upt/ch06_06.htm)

TZ kann man in UNIX System setzten und das steht für TIMEZONE. Die Date and time Extension versucht in PHP < 5.4, wenn keine Default Timezone gesetzt ist die TZ Environment Variable ausulesen und diese dann zu benutzen. Ob TZ gesetzt ist können wir nicht prüfen, aber wir können prüfen ob TZ per `putenv` gesetzt wird.
