### ISSUE TITLE
Optional limit parameter to debug_backtrace & debug_print_backtrace

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#12]
[Changed Functions](http://www.php.net/manual/en/migration54.parameters.php):

> Added the optional limit parameter to debug_backtrace() and debug_print_backtrace(), to limit the amount of stack frames returned.

Therefore it must be checked if theses methods are used within the code and make use of the second parameter `limit` which would change the behavior of these methods now.

**Comment by Ephigenia** [comment]
Wenn das ein neuer Parameter ist und wir davon ausgehen, dass der Code den man mit Jagger untersucht fehlerfrei ist, dann müssen wir hier gar keinen Sniff fabrizieren. Richtig?

**Comment by reneoelke** [comment]
Korrekt. PHP 5.3 wirft einen Fehler (`PHP Warning:  debug_backtrace() expects at most 1 parameter, 2 given in php shell code on line 1`), wenn man einen 2. Parameter verwendet.
