### ISSUE TITLE
Intl: Two new parameters for idn_to_ascii & idn_to_utf8

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#13]
[Changed Functions](http://www.php.net/manual/en/migration54.parameters.php):

> [idn_to_ascii()](http://www.php.net/manual/en/function.idn-to-ascii.php) and [idn_to_utf8()](http://www.php.net/manual/en/function.idn-to-utf8.php) now take two extra parameters, one indicating the variant (IDNA 2003 or UTS #46) and another, passed by reference, to return details about the operation in case UTS #46 is chosen.

Therefore all calls to theses methods must be checked if they use these two extra parameters because their behavior is changed now.

**Comment by Ephigenia** [comment]
Dieser Sniff muss gucken ob ein zweiter oder dritter Parameter übergeben wird und somit das Verhalten beeinflusst sein kann. Es ist sehr unwahrscheinlich aber möglich. Richtig?

``` php
<?php
idn_to_ascii('döner', 0, $something, $info);
?>
```

**Comment by reneoelke** [comment]
Leider kann man auf php.net nicht schauen, wie die Dokumentation zum Zeitpunkt PHP 5.3 aussah. Daher habe ich 
mal kurz mit PHP 5.3 geschaut, wie viele Parameter erwartet werden (`php --rf idn_to_ascii` und `php --rf idn_to_utf8`). Angeblich sind es 3 Parameter:

```
php --rf idn_to_ascii
Function [ <internal:intl> function idn_to_ascii ] {
    - Parameters [3] {
        Parameter #0 [ <required> $domain ]
        Parameter #1 [ <optional> $option ]
        Parameter #2 [ <optional> $status ]
    }
}

php --rf idn_to_utf8
Function [ <internal:intl> function idn_to_utf8 ] {
    - Parameters [3] {
        Parameter #0 [ <required> $domain ]
        Parameter #1 [ <optional> $option ]
        Parameter #2 [ <optional> $status ]
    }
}
```

Wenn man das aber testet, meldet PHP einen Fehler:

```
php -r "echo idn_to_ascii('täst.de', 22, 33) . PHP_EOL;"
PHP Warning:  idn_to_ascii() expects at most 2 parameters, 3 given in Command line code on line 1
Warning: idn_to_ascii() expects at most 2 parameters, 3 given in Command line code on line 1
```

Also denke ich, dass die Funktion eigentlich nur 2 Parameter erwartete. Daher muss man nichts prüfen, weil die beiden neuen Parameter nur die API der Funktion erweitern und nicht ändern.

**Comment by Ephigenia** [comment]
Aber es kann ja trotzdem sein, dass man in seiner Applikation `idn_to_ascii` mit drei oder mehr parametern drin hat. Man sieht die Warning ja nur wenn man sie auch im `error_reporting` angestellt hat oder? Also doch auf Vorhandensein des dritten Parameters testen?

**Comment by reneoelke** [comment]
Das ist eine prinzipielle Frage: Geht man davon aus, dass der Code fehlerfrei in Sinne von "alle Fehlertypen werden angezeigt" ist? Oder ist er fehlerfrei, weil bestimmte Fehler noch nie erkannt bzw. produziert wurden? Letztere Annahme würde uns das Leben recht schwer machen.

Wir müssten prinzipiell bei allen Funktionen, die neue Parameter bekommen haben, entsprechend prüfen. So was zu erkennen, ist eigentlich eher nen "Zusatz-Feature". Wir sollten zunächst davon ausgehen, dass der Code wirklich komplett fehlerfrei ist.

**Comment by Ephigenia** [comment]
Okay. Wenn wir davon ausgehen das der Code vorher fehlerfrei war müssen wir hier auch keinen Sniff bauen.
