### ISSUE TITLE
Converting String to Array throws E_NOTICE

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#14]
[Backward Incompatible Changes](http://www.php.net/manual/en/migration54.incompatible.php):

> Converting an array to a string will now generate an E_NOTICE level error, but the result of the cast will still be the string "Array".

So there must be a sniff that searches for array to string conversions.

**Comment by Ephigenia** [comment]
Wie könnte man diesen Sniff wohl angehen. Man muss da ja wissen das eine Variable ein Array ist. Das ist glaub ich nicht so einfach möglich.

**Comment by reneoelke** [comment]
$foo = array('foo');
   $bar = (string)$foo;

Wenn man vernachlässigt, was der Inhalt der Variablen `$foo` ist und allgemein nach dem Cast-Operator `(string)` sucht, wird man vermutlich zu viele Treffer erhalten. Daher macht es keinen Sinn, diese Art der Token-Erkennung zu verwenden.

Und da CodeSniffer keine einfache Möglichkeit bietet, den Typ bzw. Inhalt einer Variablen zu erfragen, macht es auch keinen Sinn, einen Sniff dafür zu schreiben.
