### ISSUE TITLE
Safe Mode no longer supported

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#16]
[Safe Mode](http://www.php.net/manual/en/features.safe-mode.php) is no longer supported. So there are a lot of [Configuration Settings](http://www.php.net/manual/en/ini.sect.safe-mode.php) that are not supported anymore and a [list of functions that are not restricted or disabled](http://www.php.net/manual/en/features.safe-mode.functions.php) anymore.

What do we do about it?

**Comment by Ephigenia** [comment]
wie können wir das testen?

**Comment by reneoelke** [comment]
Theoretisch könnte man Ini-Settings testen, wenn diese per ini_set() gesetzt werden dürfen. Im Falle von `safe_mode*` ist dies aber nicht möglich (`PHP_INI_SYSTEM`). Wir sollten kurz darüber diskutieren, welche Möglichkeiten es gibt.

Eine passende Lösung sollten wir aber finden, denn damit würden wir uns wieder ein wenig von den anderen Lösungen abheben. Genau solche Unterschiede sollten wir dann hervorheben und darzustellen, was wir anders machen.

**Comment by Ephigenia** [comment]
Ich bin jetzt mal die Liste [Functions restricted/disabled by safe mode](http://www.php.net/manual/en/features.safe-mode.functions.php) durchgegangen und es gibt eigentlich keine Funktion in potentiellen Applikationen die sich ohne den Safe Mode jetzt anders verhalten würden. Die meisten prüfen auf dei gleich UUID von Dateien. Andere Funktionen werden in Applikation in denen SAFE_MODE an ist wahrscheinlich eh keine Verwendung finden und wenn doch dann waren sie wirkungslos. Kannst Du auch noch mal die Liste gegenchecken und ggf. was zu Sniffs sagen die wir erstellen müssten?

**Comment by reneoelke** [comment]
Man muss sich quasi nur vorstellen: "Wie sieht eine PHP-Anwendung aus, die mit aktivem safe_mode läuft? Und müsste diese dann aussehen, wenn safe_mode nicht mehr existiert?"
- Alle Prüfungen bzgl. UID und GID schränken die Anwendung ohne safe_mode nicht ein. Ein Entwickler könnte sich jedoch mit aktiviertem safe_mode auf diese Prüfungen verlassen haben. Man könnte nach den entsprechenden Funktionen suchen und ein Warning ausgeben (z.B. "Es gibt keinen safe_mode mehr. Daher wird auch keine UID/GID-Prüfung durchgeführt. Bei Bedarf muss diese Prüfung manuell durchgeführt werden."). Das macht meines Erachtens keinen Sinn, da man nicht weiß, ob die Anwendung vorher mit aktiviertem safe_mode lief. Um dies zu wissen, bräuchte man mehr Infos (entweder per CLI-Parameter oder mit php.ini usw.).
- Bei Funktionen, die mit safe_mode nicht verwendet werden konnten (z.B. dl() oder shell_exec()), kann man davon ausgehen, dass diese auch nicht im Code vorhanden sind. Also braucht man da auch keine speziellen Prüfungen durchführen.
- Bei Verwendung der Funktion header() wird dem Header "WWW-Authenticate" die UID des laufenden PHP-Skriptes zum Realm hinzugefügt. Dieser UID-Wert fehlt bei nicht vorhandenem safe_mode. Sollte also im Code darauf reagiert oder geprüft werden, muss darauf hingewiesen werden, dass dies geändert werden muss. Wie genau die Header-Werte aussehen, muss man eventuell mit einem Testskript prüfen.
- Die $_SERVER-Variablen PHP_AUTH_USER, PHP_AUTH_PW und AUTH_TYPE stehen bei aktivem safe_mode nicht zur Verfügung. Stattdessen kann man aber noch REMOTE_USER verwendet werden, um einen authentifizierten Benutzer zu ermitteln. Man könnte prüfen, ob diese Variable verwendet wird und dann entsprechend eine Warnung / Notiz ausgeben, z.B. "REMOTE_USER wird verwendet. Da safe_mode nicht mehr existiert, können auch die Variablen PHP_AUTH_USER, PHP_AUTH_PW und AUTH_TYPE verwendet werden."
- In der mail() Funktion darf bei aktivem safe_mode nicht der 5. Parameter verwendet werden. Man könnte eine Warnung / Notiz ausgeben, dass dies nun möglich ist. Ist aber fraglich, ob das Sinn macht, da man nicht weiß, ob vorher safe_mode aktiv war oder nicht.
- Man sollte prüfen, ob bestimmte Ini-Settings bzgl. safe_mode ausgelesen werden: safe_mode, safe_mode_gid, safe_mode_include_dir, safe_mode_exec_dir, safe_mode_allowed_env_vars, safe_mode_protected_env_vars. Wenn dem so ist, dann muss man eine entsprechende Meldung ausgeben. Ist zu klären, ob man eine Warnung oder einen Fehler ausgibt.

**Comment by Ephigenia** [comment]
Ich hab jetzt für die Sachen bei denen ich meine, dass es ein Sniff werden sollte jeweils eine neue Issue angelegt um die Sachen aufzuteilen: 
- #43 header() Testscript
- #44 $_SERVER AUTH Variable
- #45 Safe Mode INI Einstellungen suchen

Da die anderen Sachen nicht prüfbar oder unsinnig sind zu prüfen schliesse ich diese Issue jetzt auch.
