### ISSUE TITLE
Changed Behavior: array_combine

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#17]
[Backward Incompatible Changes](http://www.php.net/manual/en/migration54.incompatible.php)

> `array_combine` returns `array()` instead of false when two empty arrays are provided

**Comment by Ephigenia** [comment]
Man könnte ziemlich einfach einen Sniff schreiben der sowas findet:

``` php
<?php
array_combine(array(), array());
```

Aber sobald die Parameter Variablen sind wird es wieder schwierig da man nicht genau sagen kann ob das Arrays sind. Macht es dann Sinn bei Aufrufen wie dem folgenden einfach eine Warning zu werfen?

``` php
<?php
array_combine($var, $second);
```

**Comment by reneoelke** [comment]
Man sollte nur mit einer Meldung reagieren, wenn der Rückgabewert verarbeitet wird (`$result = array_combine($ar1, $ar2);` oder `return array_combine($ar1, $ar2);`). Oder wenn die Funktion im Kontext eines Control-Statements (if / else if, switch, while/do, for, foreach) verwendet wird. Dabei ist es unerheblich, ob die Parameter leere Arrays sind oder nicht. Wenn sie einfach nur so aufgerufen wird, kann man sie vernachlässigen.

**Comment by Ephigenia** [comment]
Das mit dem Rückgabewert ist doch wieder schwierig! Da muss man doch wieder mit den Sniffer gucken ob eine Zuweisung stattfindet und dann die Verwendung der Variablen weiterverfolgen.

Das mit der IF-Anweisung geht vielleicht - ist aber auch nicht gerade einfach.

**Comment by reneoelke** [comment]
Die Verwendung der Variablen muss man nicht weiter verfolgen. Allein, dass eine Zuweisung stattfindet (also der Rückgabewert von `array_combine()` verwendet wird), ist eine Warnung wert. Immer mit dem Hinweis, dass es nur dann ein Problem gibt, wenn die beiden Arrays leer waren. Der Entwickler ist auf jeden Fall gezwungen, nachzuschauen.

**Comment by Ephigenia** [comment]
okay, dann suchen wir nach der Verwendung von `array_combine()` und geben eine Warning aus. Ich übernehme das dann.

**Comment by Ephigenia** [comment]
Ich hab jetzt den array_combine sniff committet:
https://github.com/foobugs/jagger/commit/0135c398115599b734f32e786f69e7f44d0afdb3

allerdings ist es mir noch nicht klar wie man nach der "Zuweisung" checkt. Es gibt so viele Möglichkeiten die nicht passen.
