### ISSUE TITLE
PHP 5.4 Virtuelle Machine

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#19]
Um ein Paar Funktionalitäten und Unklarheiten zu beseitigen wäre es super eine Virtuelle Umgebung mit PHP 5.4 zu haben in der man bestimmte Dinge testen kann (z. Bsp. #3). Kannst Du bitte ein Shell Script für eine normale Ubuntu Kiste erstellen welches automatisch PHP 5.4 installiert?

**Comment by reneoelke** [comment]
Ich vermute mal, Du meinst ein Skript für Vagrant oder so.

Das Problem ist, dass noch keine der Ubuntu- oder Debian-Releases PHP 5.4 offiziell unterstützt. Man müsste ein externes Package-Repository hinzufügen oder es selber kompilieren. Die andere Alternative wäre, Zend Server zu installieren. In der aktuellen Version 5.6 Technology Preview wird PHP 5.4 unterstützt (30 Tage kostenlos, danach automatischer Switch auf Community Edition).

**Comment by Ephigenia** [comment]
Ist das nicht erledigt?
