### ISSUE TITLE
Namespace detection

### ISSUE THREAD

**Issue by reneoelke** [reneoelke/Php53to54#26]
It should be possible to detect the namespace of a file / class. If detected, then all definitions (class, functions, constants, interfaces) should be checked against global namespace.

**Comment by Ephigenia** [comment]
Die Namespace detection funktioniert wenn man `T_NAMESPACE` noch in `register` registriert und aufnimmt. Allerdings werden tatsächlich die `process` funktionen nacheinander mit dem selben Sniff aufgerufen. Wenn man etwas in dem Sniff setzt muss man darauf achten dass alles Datei-abhängig ist. Egal … man bekommt es trotzdem hin in dem man den letzten Namespace in einer variablen speichert die auch den Dateinamen mit ablegt. Danach kann man super abfragen ob man gerade in einem Namespace ("in der datei") ist oder nicht.

Der Code für den Namespace ist super redundant jetzt. In
- ForbiddenClassNamesSniff
- ForbiddenConstantNamesSniff
- ForbiddenInterfaceNamesSniff

ist für die namespace detection der selbe code drin … das hab ich jetzt auch als #27 angelegt

**Comment by Ephigenia** [comment]
Bei dem Sniff der Funktionen behandelt und rausfindet ob sie Deprecated oder sonstwas sind, also vor allem die Aufrufe benutze ich bisher `Generic_Sniffs_PHP_DeprecatedFunctionsSniff` der aber keine Namespaces abcheckt oder genau schaut ob es auch ein Funktionsaufruf ist. Hier brauchen wir auch eine richtige Genereic Klasse die das abcheckt.

**Comment by Ephigenia** [comment]
Namespace Detection wird so gut wie überall verwendet werden müssen. Die Deprecated/Klassen werden auch checken müssen ob sie in einem Namespace liegen:
https://github.com/foobugs/jagger/tree/master/Standards/PHP53to54/Sniffs/Deprecated

**Comment by Ephigenia** [comment]
Für die beiden Sniffs in Deprecated ist auch die neue Issue #38 zuständig. Das kann dann hier auch zu.
