### ISSUE TITLE
break+continue do not accept variable arguments anymore

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#3]
[Backward Incompatible Changes](http://www.php.net/manual/en/migration54.incompatible.php):

> The break and continue statements no longer accept variable arguments (e.g., `break 1 + foo() * $bar;`). Static arguments still work, such as `break 2;`.

invalid code:

``` php
    break 1 + foo() * $bar;
```

**Comment by Ephigenia** [comment]
Variablen sind nicht erlaubt, aber gilt das auch für Funktionsauffrufe, Statische Klassen Methoden Aufrufe, oder Methoden-Aufrufe? Das müsste man mal in PHP 5.4 ausprobieren.

``` php
<?php
for($i = 0; $i < 100; $i++) {
    continue getContinue();
}

for($i = 0; $i < 100; $i++) {
    continue $object->getContinue();
}

for($i = 0; $i < 100; $i++) {
    continue staticObject::getContinue();
}
```

**Comment by Ephigenia** [comment]
ich hab es jetzt erstmal so gebaut, dass auch die oben genannten calls gecheckt werden und als warning ausgegeben werden

**Comment by reneoelke** [comment]
Okay. Sollte es unter PHP 5.4 ein anderes Verhalten geben, können wir das immer noch ändern.

Unter PHP 5.3 funktioniert folgender Code problemlos:

``` php
<?php

function getContinue()
{
  return 1;
}

class MyClass
{
  public function __construct()
  {
    for ($i = 0; $i < 100; $i++) {
      break getContinue();
    }

    for ($i = 0; $i < 100; $i++) {
      break $this->getContinue();
    }
  }

  public function getContinue()
  {
    return 1;
  }

  public static function doContinue()
  {
    return 1;
  }
}

$object = new MyClass();

for ($i = 0; $i < 100; $i++) {
    break $object->getContinue();
}

for ($i = 0; $i < 100; $i++) {
    break MyClass::doContinue();
}
```

Wie es sich damit unter PHP 5.4 verhält, muss noch getestet werden.

**Comment by Ephigenia** [comment]
Jup, solchen Code hatte ich schon getestet :)

**Comment by reneoelke** [comment]
Ich habe obigen Code mit PHP 5.4 getestet (erstmal nur im Zend Studio mit dem dort enthaltenen PHP-Interpreter). Es gibt eine Fehlermeldung:

``` text
Fatal error: break operator with non-constant operand is no longer supported in ../test-break.php on line 13
```

Die Warnungen können also in Fehlermeldungen umgewandelt werden.

**Comment by Ephigenia** [comment]
Okay, das ist super, dass wir jetzt wissen was alles nicht geht. Wir könnten aber den [Sniff](https://github.com/foobugs/jagger/blob/master/Standards/PHP53to54/Sniffs/PHP/BreakContinueVarSyntaxSniff.php) wie er jetzt ist umdrehen indem er nicht nach break und dann falschem sucht, sondern eher nach etwas richtigem – Dann wäre die Frage was das richtige ist, und laut der Fehlermeldung 

> Fatal error: break operator with non-constant operand is no longer supported in ../test-break.php on line 13

darf man nichts anderes als `non-constant operand` angeben. Da ich nichts finden konnte was das genau sein soll schlage ich vor, wir untersuchen was die einzig positiven Möglichkeiten von dem Sniff sind. Also was auf `break` in PHP 5.4 noch funktioniert.

Ich vermute das folgende Sachen die einzigen erlaubten Sachen sind?

``` php
<?php
break (2);
break 2;
break 22;
```

Was meinst Du?

**Comment by goatherd** [comment]
Korrekt.
Erlaubt sind nur noch natürliche Zahlen (int > 0).

(die PHP-Dokumentation ist offensichtlich falsch, wenn von `continue 0;` oder `break 0;` die Rede ist).
