### ISSUE TITLE
Non-Numeric Offset on String

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#30]
> Non-numeric string offsets - e.g. $a['foo'] where $a is a string - now return false on isset() and true on empty(), and produce a E_WARNING if you try to use them. Offsets of types double, bool and null produce a E_NOTICE. Numeric strings (e.g. $a['2']) still work as before. Note that offsets like '12.3' and '5 foobar' are considered non-numeric and produce a E_WARNING, but are converted to 12 and 5 respectively, for backward compatibility reasons ([Backwards Incompatibilty Changes](http://www.php.net/manual/en/migration54.incompatible.php))

Für solch einen Sniff müsste man auch wissen was in der entsprechenden Variable drin steht. Ist tendenziell schwierig.

**Comment by reneoelke** [comment]
Im Prinzip reicht es, wenn eine Warnung ausgegeben wird, wenn im Code sowas wie `isset($foo['foo'])` oder `empty($foo['foo'])` gefunden wird. In der Form: "Es wird auf einen nicht numerischen Array-Key zugegriffen. Sollte die Variable $foo von Typ String sein, ist zu beachten, dass nun im Unterschied zu PHP < 5.4 bei isset() false und bei empty() true zurück gegeben wird."

Es wird recht kompliziert sein, genau diese Token-Kombination zu erkennen. Zu beachten ist, dass $foo['2'] bzw. $foo['42'] usw. weiterhin gültig sind. Intern wird der Key in einen Integer gecastet.

**Comment by Ephigenia** [comment]
Man wird im Code aber ziemlich of auf Stellen stoßen bei dem auf einen String Index gesucht oder getestet wird? Dann wären das ja jede Menge warning von denen 0.01% oder weniger wirklich zu beachten sind?

**Comment by reneoelke** [comment]
Man soll ja nicht nach `$foo['foo']` suchen, sondern gezielt nach der Verwendung diesen Codes innerhalb von `isset()` oder `empty()`. Das dürfte die Treffermenge schon etwas einschränken. Man kann diese Treffermenge noch weiter einschränken, wenn man den Scope betrachtet. Also wenn `isset()` oder `empty()` innerhalb von `if / else if` ausgeführt, dann macht ein Warning Sinn. Auch die Rückgabewerte von `isset()` und `empty()` können die Treffermenge einschränken. Es kann davon ausgegangen werden, dass diese Rückgabewerte später in einer if-Anweisung verwendet werden.

Das Warning immer mit dem Hinweis, dass es eventuell ein Problem sein kann, wenn sich hinter der Variablen `$foo` ein String verbirgt.

**Comment by Ephigenia** [comment]
mmh, also wir könenn das gerne probieren, aber ich glaube das es immer noch sehr viele Treffer geben wird, wenn man nach einem `if (isset($foo['bar']))` sucht. Viele Applikationen und Frameworks (ich denke da auch an CakePHP) verwenden sehr exzessiv indizierte Arrays …

**Comment by reneoelke** [comment]
Es kann sein, dass es viele Treffer geben wird. Das werden wir dann sehen und ändern können wir das dann immer noch. Auf jeden Fall haben wir aber schon mal die Treffermenge eingeschränkt. Eventuell kommentieren wir dann den Code erstmal aus und aktivieren ihn dann wieder, wenn wir das Feature, Notizen auszugeben, implementiert haben.

**Comment by Ephigenia** [comment]
okay, das ist finde ich für den ersten Release noch zu kompliziert. Was meinst Du?
