### ISSUE TITLE
Apache Compatible Functions for FastCGI SAPI

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#31]
> Added apache compatible functions: apache_child_terminate(), getallheaders(), apache_request_headers() and apache_response_headers() for FastCGI SAPI. ([Changes in SAPI modules](http://www.php.net/manual/en/migration54.sapi.php)) 
> 
> This function became available under FastCGI. Previously, it was supported only when PHP was installed as an Apache module.

Diese Funktionen sind jetzt also auch mit FastCGI / CGI Version kompatibel und erreichbar. Muss man hier überhaupt was sniffen? Ich glaube nicht oder?

**Comment by reneoelke** [comment]
Die Funktionen sind jetzt auch bei FastCGI nutzbar, von CGI ist nicht die Rede. CGI unterscheidet sich zu FastCGI.

Da man nicht weiß, in welchem SAPI Modus die PHP-Anwendung läuft, kann man hier nichts prüfen. Es sei denn, wir stellen einen CLI-Parameter zur Verfügung, mit dem man definieren kann, ob die Anwendung per FastCGI, Modul oder CGI läuft.

Eventuell könnte man prüfen, ob im Code der SAPI-Mode geprüft wird (php_sapi_name()). Wenn auf "cgi-fcgi" geprüft wird, kann man davon ausgehen, dass der FastCGI Mode relevant ist. Aber trotzdem ist es dann recht kompliziert, einen Zusammenhang zu den neu zu verwendenden Funktionen herzustellen, zumindest mit den normalen CodeSniffer-Mitteln.

**Comment by Ephigenia** [comment]
Dann bin ich dafür hier keinen Sniff zu schreiben. Schliesse diese Issue daher.
