### ISSUE TITLE
PHP 5.4 Changelog checken

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#39]
Das [PHP 5.4 Changelog](http://php.net/ChangeLog-5.php) sollte noch mal nach Änderungen durchsucht werden die uns eventuell entgangen sind.

**Comment by goatherd** [comment]
Kümmere mich darum, es noch einmal abzugleichen.

Hättet Ihr eine Liste der bereits erledigten Punkte? (könnte man z.B. ins Wiki aufnehmen. Habe mal als Entwurf einen entsprechenden Artikel angelegt).

**Comment by Ephigenia** [comment]
Wir haben damals ein Google Docs gemacht und stück für Stück alle Punkte in GitHub übertragen. Es sollten also schon alle Punkte zu denen man Sniffs schreiben kann hier vorhanden sein. Deswegen ist diese Issue eigentlich auch geschlossen ;-)

**Comment by goatherd** [comment]
Habe ich angenommen. War mehr als Erinnerung für mich gedacht, alle Schritte nachzuvollziehen, die Ihr schon gemacht habt und die tatsächliche Abdeckung der Sniffs zu verstehen.

Vielleicht nicht der beste Ort dafür. Aber ist es keine valide Option die umgesetzten Punkte aus Eurem Changelog als Feature-Beschreibung offen zu legen? Als Anwender von PHP53to54 fehlt mir bisher ein Einblick, was überhaupt geprüft wird.

**Comment by Ephigenia** [comment]
Es ist grob in der README.md umrissen: https://github.com/foobugs/PHP53to54/blob/master/README.md
