### ISSUE TITLE
default_charset changed

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#40]
Laut dem [PHP Changelog](http://php.net/ChangeLog-5.php) hat sich die INI-Direktive `default_charset` von 'ISO-88591-1`auf`UTF-8` geändert:

> Changed default value of "default_charset" php.ini option from ISO-8859-1 to UTF-8.

Der `default_charset` wird automatisch im Header der Response gesetzt. ([siehe](http://www.php.net/manual/de/ini.core.php#ini.default-charset))

Sollte man hier vielleicht darauf prüfen ob der `default_charset` irgendwo ausgelesen wird oder welche funktionen hier beeinfluss werden?

**Comment by reneoelke** [comment]
Es geht in erster Linie um die Funktionen `htmlspecialchars()` und `htmlentities()`. Und nicht um das INI-Setting `default_charset`. Letzteres wurde meiner Meinung nach nicht auf UTF-8 gesetzt. `default_charset` beeinflusst nicht die Funktionen `htmlspecialchars()` und `htmlentities()`, es sei denn, deren encoding-Parameter ist leer `""`. Zitat: "An empty string activates detection from script encoding (Zend multibyte), default_charset and current locale (see nl_langinfo() and setlocale()), in this order. Not recommended."

Es gibt also 2 Dinge, die zu prüfen sind:
- Wenn den Funktionen `htmlspecialchars()` und `htmlentities()` kein encoding-Parameter übergeben wird. Dann hat sich das Verhalten gegenüber PHP 5.3 geändert (von ISO auf UTF-8).
- Wenn den Funktionen `htmlspecialchars()` und `htmlentities()` ein leerer String als encoding-Parameter übergeben wird. Dann hängt es davon ab, was u.a. in `default_charset` gesetzt ist. Eventuell wäre es sinnvoll, zu ermitteln, ob vorher `default_charset` gesetzt wird. Das ist aber wiederum sehr schwer mit den aktuellen Mitteln vom CodeSniffer möglich.

**Comment by Ephigenia** [comment]
Den ersten Fall habe ich schon in #33 abgegessen. Da prüfe ich auf die Verwendung des dritten Parameters.

Für den zweiten Fall muss man noch einen Sniff schrieben oder es in den Vorhandenen Einbauen, dass er dort auch auf einen leeren String `""` prüft.
