### ISSUE TITLE
short_open_tag always enabled

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#41]
Short Open Tags (`short_open_tag`) sind jetzt default mässig immer erlaubt. Die [INI-Option dafür](http://www.php.net/manual/de/ini.core.php#ini.short-open-tag) ist damit hinfällig. Ich hab `short_open_tag` jetzt in die nicht mehr erlaubten INI-Direktiven hinzugefügt. Muss man noch was prüfen – XML Dateien im Source die mit short open tag sind oder sowas?

**Comment by reneoelke** [comment]
Meiner Meinung nach, war `short_open_tag` auch vorher schon erlaubt (Default auf `On` gestellt). Soweit ich das verstanden habe, ist `short_open_tag` auch weiterhin erlaubt. Also ist `short_open_tag` weiterhin erlaubt, kann also aus den nicht mehr erlaubten INI-Direktiven wieder entfernt werden.

Man sollte im Code prüfen, ob `short_open_tag` mittels `ini_set()` bzw. auch `ini_get()` verwendet wird. Im Falle von `ini_set()` kann man prüfen, ob auf das neue Default-Verhalten gesetzt wird. In dem Falle kann man eine Meldung ausgeben, dass dies nicht mehr nötig ist, es sei denn, in der php.ini ist explizit ein anderer Wert gesetzt worden.

Was wesentlich interessanter ist (siehe http://de.php.net/manual/en/migration54.new-features.php), ist folgende Aussage: "<?= is now always available, regardless of the short_open_tag php.ini option." Findet man also im Code ein `T_OPEN_TAG_WITH_ECHO` das dem `<?=` entspricht, dann kann man eine Meldung ausgeben, dass dies auch bei gesetztem `short_open_tag = Off` verwendet werden kann. Man muss also vorher im PHP-Code nicht mehr `ini_set('short_open_tag', 'On')` setzen.

**Comment by Ephigenia** [comment]
Okay, also ist hier die Aufgabe einen Sniff zu schreiben der nach `ini_set('short_open_tag', 'On')` sucht und dann eine Warning ausgibt, dass man das nicht mehr machen muss, da short_open_tags nicht mehr relevant ist?

**Comment by reneoelke** [comment]
Im Prinzip ja. Aber ich würde nicht sagen, dass es nicht mehr relevant ist. Es ist weiterhin relevant. Eine Meldung in der Form wäre passender: "Das Setzen der Konfigurationsoption 'short_open_tag' auf 'On' ist nicht mehr nötig, da dies die Standardeinstellung ist. Es sei denn, diese Option wurde vorher bzw. in der php.ini auf 'Off' gesetzt."
