### ISSUE TITLE
null/''/false silent casting now generates warning

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#42]
In dem [PHP Changelog](http://php.net/ChangeLog-5.php) steht:

> Changed silent casting of null/''/false into an Object when adding a property into a warning.

Das müssen wir mal ausprobieren und dann überlegen wie man einen Sniff dafür schreiben kann.

**Comment by reneoelke** [comment]
Das können wir nur prüfen, wenn wir wissen, wie dieses silent casting realisiert wird. Dann müssen wir dies sowohl unter PHP 5.3 und PHP 5.4 testen. Erst dann wissen wir, worauf wir zu prüfen haben und was das Ergebnis bzw. die Meldung ist.

**Comment by Ephigenia** [comment]
In PHP 5.3 gibt er eine `STRICT`-Fehlermeldung aus, wenn man auf einem `null`, `""` oder `false` versucht eine Property zu setzen:

``` php
<?php
$myVar = "";
$myVar->something = 'foobugs';
```

Gibt folgenden Fehler aus:

``` text
PHP Strict standards:  Creating default object from empty value in php shell code on line 1
```

Da das wieder mit dem Inhalt von Variablen zu tun hat denke ich dass wir das wieder nicht testen können.

**Comment by reneoelke** [comment]
Wenn statt einer Strict-Fehlermeldung nun eine Warning-Fehlermeldung kommt, ist das Verhalten eigentlich gleich geblieben. Da wir das sowieso nicht testen können, weil das abhängig zum Inhalt der Variablen ist, können wir das ignorieren.
