### ISSUE TITLE
header() TestScript

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#43]
Wie in #16 von @reneoelke erwähnt, brauchen wir um die Auswirkungen vom Safe Mode auf die `header` Funktion zu testen ein Testscript um dann feststellen zu können was wir hier für einen Sniff programmieren müssen. Kannst Du das Testscript mal anlegen und schauen bitte?

**Comment by reneoelke** [comment]
Werde ich machen. Allerdings hängt dieser Issue von #19 ab. Es muss zuerst eine Runtime-Umgebung geben, in der wir PHP 5.4 ausführen können.
