### ISSUE TITLE
$_SERVER AUTH-Variables

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#44]
#16 von @reneoelke

> Die $_SERVER-Variablen PHP_AUTH_USER, PHP_AUTH_PW und AUTH_TYPE stehen bei aktivem safe_mode nicht zur Verfügung. Stattdessen kann man aber noch REMOTE_USER verwendet werden, um einen authentifizierten Benutzer zu ermitteln. Man könnte prüfen, ob diese Variable verwendet wird und dann entsprechend eine Warnung / Notiz ausgeben, z.B. "REMOTE_USER wird verwendet. Da safe_mode nicht mehr existiert, können auch die Variablen PHP_AUTH_USER, PHP_AUTH_PW und AUTH_TYPE verwendet werden."

Dann seh’ ich das richtig, dass wir einen Sniff brauchen der nach der Verwendung von `REMOTE_USER` suchen sollten und dann einfach die Warning ausgeben?

**Comment by reneoelke** [comment]
Ja, genau. Ist nur schade, dass man keine Notices ausgeben kann. Denn eine Warning ist es ja eigentlich nicht. Wenn wir Notices haben wollen, müssten wir CodeSniffer erweitern. Ich mache dafür mal einen neuen Issue auf, der eher längerfristig gedacht ist.

**Comment by Ephigenia** [comment]
Für den ersten Schritt machen wir hier aber erstmal eine Warning draus ok?
