### ISSUE TITLE
autoloading

### ISSUE THREAD

**Issue by goatherd** [reneoelke/Php53to54#50]
Sehe am letzten commit, dass ihr mit require_once arbeitet, um Klassen nachzuladen.

Was haltet ihr von https://wiki.php.net/rfc/splclassloader ?

Für gelegentliches Ausführen auf der Shell bringt das zwar keinen Geschwindigkeitsvorteil, reduziert aber Code und spart etwas Zeit bei der Sniff-Erstellung.

Habe das bisher nicht geprüft, aber könnte man nicht statt eines einzelnen Sniffs das bootstrapping aufrufen und das Sniff per Klassennamen angeben. 

Also etwas wie:
  `phpcs --standard=PHP53to54 --sniff=PHP53to54.Generic.ForbiddenConstantNames <source-path>`

In eurem Beispiel muss man ja den kompletten Pfad angeben, was aber durch das RuleSet gar nicht nötig ist.

**Comment by Ephigenia** [comment]
Die Krücke mit require_once ist eine ganz schlechte - das ist mir bewusst. Ich habe es nur schnell eingebaut um auf der Kommandozeile den externen Standard erstmal testen zu können weil ich den neuen break/continue Sniff ausprobieren wollte. Das ging dann jetzt erstmal.

Für das Problem mit den nicht gefundenen Sniffs in dem ruleset.xml müssen wir uns etwas einfallen lassen. Wenn wir kein Ruleset benutzen können in dem wir Einstellungen zu unseren Sniffs machen können werden wir recht unflexibel. Leider schient der Codesniffer es nicht vorzusehen das man in dem Ruleset Sniffs referenziert die in einem externen Ordner liegen und ignoriert diese obwohl sie mit `--standard=[vollerPfad]` angegeben sind.

**Comment by goatherd** [comment]
War mir nicht bewusst. Bin ganz naiv von der CodeSniffer Dokumentation ausgegangen.
Notiere mir gleich ein Issue, dass mal im Detail zu prüfen. Vielleicht kann man es (trivial) patchen.

Die require_once sonst für einen späteren Release zu eliminieren ist etwas müßige Arbeit, aber gut: _Release early, release often_.
