### ISSUE TITLE
schnellerer in_array Test

### ISSUE THREAD

**Issue by goatherd** [reneoelke/Php53to54#51]
Kleiner Benchmark als Gegenargument für:
`if ( in_array($key, array(1,2,3) )`

Empfehlung:
- `array(1=>true,2=>true,3=>true)` als Property der Klasse **oder** Property + `array_flip`
- `isset` statt `in_array`

Ist etwas überoptimiert (in_array ist an sich ausreichend schnell), aber es ist um Faktor 10 schneller! Für's Zend-Framework wartet man eine halbe Sekunde länger!
Kann man das so stehen lassen?

Benchmark:

```
in_array:            0.70s
isset:               0.38s
in_array (prepared): 0.29s
isset (prepared):    0.05s
```

Code:

``` php
<?php
/** Iterative testing of in_array vs isset each prepared and unprepared. */

$iterations = 1000000; // 10 000 000 

$n = $iterations;
$t10 = microtime(true);
do {
    in_array('world', array('hello', 'world', 'test')) ;
} while ($n-->1);
$t11 = microtime(true);

$n = $iterations;
$t20 = microtime(true);
do {
    $keys = array('hello'=>true, 'world'=>true, 'test'=>true);
    isset($keys['world']);
} while ($n-->1);
$t21 = microtime(true);

$keys = array('hello', 'world', 'test');
$n = $iterations;
$t30 = microtime(true);
do {
    in_array('world', $keys);
} while ($n-->1);
$t31 = microtime(true);

$keys = array_flip($keys);
$n = $iterations;
$t40 = microtime(true);
do {
    isset($keys['world']);
} while ($n-->1);
$t41 = microtime(true);

printf('in_array:            %.2fs' . PHP_EOL, $t11-$t10);
printf('isset:               %.2fs' . PHP_EOL, $t21-$t20);
printf('in_array (prepared): %.2fs' . PHP_EOL, $t31-$t30);
printf('isset (prepared):    %.2fs' . PHP_EOL, $t41-$t40);
```

**Comment by Ephigenia** [comment]
Wo würdest Du das im PHP53to54 genau anbringen?

**Comment by goatherd** [comment]
Finde keine Markdown-Syntax für Diffs oder Code-Zeilen. Schade:

Zeile 74 in / Sniffs / PHP / BreakContinueVarSyntaxSniff.php :
`if (!in_array($nextToken['code'], array(T_WHITESPACE, T_LNUMBER, T_SEMICOLON)))`

Darüber kann man auch noch etwas rausholen (30% für PHP 5.2, 20% für 5.4):

`for ($curToken = $stackPtr + 1; $curToken < $nextSemicolonToken; $curToken++) { ... }`
while ist schneller (und leichter zu lesen):

``` php
$curToken = $stackPtr + 1;
while($curToken ++ < $nextSemicolonToken) { ... }
```

Sind aber nur Hinweise für schnellere Coding-Praktiken. Deine Klassen sind völlig korrekt.

**Comment by Ephigenia** [comment]
Du kannst wenn Du über den GitHub-Code-Browser direkt zur Datei gehst auch einfach Anmerkungen in einer Zeile machen. Einfach die Zeilennummer anklicken: https://github.com/foobugs/PHP53to54/blob/master/Sniffs/PHP/BreakContinueVarSyntaxSniff.php

Vielen Dank für die Hinweise. Du kannst die Sachen eigentlich auch gleich selbst verändern. Zugriff auf das Repo hast Du doch oder?

**Comment by goatherd** [comment]
Nein, habe keinen Zugriff.

Zumindest ging mein edit-Versuch gerade verloren.

Kann es später noch einmal probieren. Aber wenn ich schon dabei bin: wie teste ich, ob die Zahl > 0 ist?
`continue/ break 0;` ist in PHP 5.4 nicht mehr untersützt.

**Comment by Ephigenia** [comment]
Ich hab’ Dich jetzt mal als Entwickler zu dem Repository hinzugefügt. Da es öffentlich ist kann es jeder einfach Forken und darin editieren was er will. Du müsstest jetzt aber das Repo auch so clonen können.

Für die Überprüfung ob > 0 kannst du in dem $token Array den content abfragen. Also sowas wie

``` php
if ($token['content‘] == '0') ...
```

**Comment by Ephigenia** [comment]
Du hast das Repo auch schon geforkt (https://github.com/goatherd/PHP53to54). Wenn Du darin Änderungen machst kannst Du sie als Pull-Request wieder an das Ursprungsrepository schicken.

**Comment by goatherd** [comment]
Danke. Hatte zunächst versucht es direkt zu editieren, weil es (zumindest beim ersten mal) automatisch an den Fork gehen sollte. 

'0'-Test ist hinzugefügt.

Werde Ende des Monats mal ein komplettes Review der Sniffs versuchen (dann im Fork mit Pull request).
