### ISSUE TITLE
Conding Standard

### ISSUE THREAD

**Issue by goatherd** [reneoelke/Php53to54#53]
Okay, hier der phpcs Report für
Zend: A TOTAL OF 1068 ERROR(S) AND 68 WARNING(S) WERE FOUND IN 25 FILE(S)
PEAR: A TOTAL OF 2451 ERROR(S) AND 52 WARNING(S) WERE FOUND IN 25 FILE(S)

Welchem CodingStandard soll euer Programm entsprechen?
Bei der fehlenden inline-Dokumentation, Inkonsistenzen und unersichtlichem Tab-Einsatz war ich schon aktiv.

**Comment by goatherd** [comment]
Habe erst einmal PEAR Standards umgesetzt (weil naheliegend) und werde das gleich in meinen Fork schieben.

**Comment by Ephigenia** [comment]
fork hab ich angenommen
