### ISSUE TITLE
RemoteUserSniff.php: incorrect literal check.

### ISSUE THREAD

**Issue by goatherd** [reneoelke/Php53to54#54]
```
# phpcs --standard=PHP53to54 ./PHP53to54/Sniffs/

FILE: ./PHP53to54/Sniffs/PHP/RemoteUserSniff.php
--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 70 | WARNING | REMOTE_USER is deprecated as SAFE_MODE was removed
--------------------------------------------------------------------------------

#70      if ($content == 'REMOTE_USER')
```

Is that desired?

**Comment by Ephigenia** [comment]
Boar ich bin mir gerade nicht mehr sicher wieso wir hier überhaupt darauf prüfen wieso es REMOTE_USER gibt? Das ist ja nur gesetzt wenn man safe_mode on hat.

**Comment by goatherd** [comment]
REMOTE_USER ist doch ein gutes Indiz, dass safe_mode Code vorhanden ist und könnte/ sollte bei der Migration beachtet/ entfernt werden. Sichergehen, dass auch ein safe_mode-Test vorab gemacht wurde kann man ja nicht.

Habe die Meldung in meinem branch behoben (`'REMOTE' . '_USER'`) und werde es "später" mit ein paar mehr Tests in den master kopieren.
