### ISSUE TITLE
New reserved Keywords

### ISSUE THREAD

**Issue by Ephigenia** [reneoelke/Php53to54#6]
[Backward Incompatible Changes](http://www.php.net/manual/en/migration54.incompatible.php):

> The following keywords are now reserved, and may not be used as names by functions, classes, etc. `trait`, `callable`, `insteadof`

How can we check that?

**Comment by Ephigenia** [comment]
man könnte das lgaub ich mit T_STRING abfangen und dann gucken was davor oder danach steht … was für ein keyword spricht wären:
- T_WHITSPACE
- Aufgehende Klammern davor oder T_STRING davor (andere klasse oder interface) ?

**Comment by Ephigenia** [comment]
was muss man hier eigentlich genau überprüfen?

**Comment by reneoelke** [comment]
Man muss prüfen, dass keine Funktionen, Klassen etc. mit obigen Namen definiert sind. Unter folgender URL http://www.php.net/manual/en/reserved.keywords.php steht "You cannot use any of the following words as constants, class names, function or method names. Using them as variable names is generally OK, but could lead to confusion.".

Man sucht also nach T_STRING, denen vorher ein T_CONST, T_CLASS oder T_FUNCTION vorangestellt ist (inkl. T_WHITESPACE). Oder aber die innerhalb der define() Funktion verwendet werden.

**Comment by Ephigenia** [comment]
Ah okay, dann hab ich das verstanden. Kann ich programmieren.

**Comment by Ephigenia** [comment]
ich hab mich an dem sniff den es für php 5.2-5.3 gab orientiert, bin mir aber nicht sicher ob damit alle möglichen fälle abgedeckt sind: https://github.com/foobugs/jagger/commit/6ffcbe80af630498dfbc4a2e7ddfa1ed951cf39b

**Comment by Ephigenia** [comment]
ich nehme das jetzt einfach mal an und schliesse diese issue
