### ISSUE TITLE
Cannot redeclare class PHP53to54_Sniffs_PHP_RemovedFunctionParametersSniff

### ISSUE THREAD

**Issue by MassiAtZend** [reneoelke/Php53to54#96]
Trying to use the library on a ZF1 based project on a MAC OSX 10.8.4 machine.
Install PHP 5.3 and 5.4 using MacPorts.

Output of 'phpcs -i' is:
The installed coding standards are MySource, PEAR, Php53to54, PHPCS, PSR1, PSR2, Squiz and Zend

The command I run is 'phpcs -vvv --standard=Php53to54 <source_code_path>' from '/opt/local/lib/php' which is the root of the PEAR libraries.
The resulting execution crashes with the following output:
Registering sniffs in Php53to54 standard...
    Registered Php53to54_Sniffs_Deprecated_FunctionAliasesSniff
    Registered Php53to54_Sniffs_Deprecated_FunctionsSniff
    Registered Php53to54_Sniffs_Extensions_SQLiteConstantsSniff
    Registered Php53to54_Sniffs_Extensions_SQLiteFunctionsSniff
    Registered Php53to54_Sniffs_Extensions_SQLiteSniff
    Registered Php53to54_Sniffs_Functions_CallTimePassByReferenceSniff
    Registered Php53to54_Sniffs_Generic_ForbiddenClassNamesSniff
    Registered Php53to54_Sniffs_Generic_ForbiddenConstantNamesSniff
    Registered Php53to54_Sniffs_Generic_ForbiddenInterfaceNamesSniff
    Registered Php53to54_Sniffs_Generic_RemovedINIDirectivesSniff
    Registered Php53to54_Sniffs_Generic_ReservedKeywordsSniff
    Registered Php53to54_Sniffs_PHP_ArrayCombineSniff
    Registered Php53to54_Sniffs_PHP_BreakContinueVarSyntaxSniff
    Registered Php53to54_Sniffs_PHP_EStrictSniff
    Registered Php53to54_Sniffs_PHP_ForbiddenFunctionNamesSniff
    Registered Php53to54_Sniffs_PHP_ForbiddenParameterSniff
    Registered Php53to54_Sniffs_PHP_HtmlentitiesAsianCharsetsSniff
    Registered Php53to54_Sniffs_PHP_INIShortOpenTagsSniff
    Registered Php53to54_Sniffs_PHP_PutenvTZSniff
    Registered Php53to54_Sniffs_PHP_RemoteUserSniff

Fatal error: Cannot redeclare class PHP53to54_Sniffs_PHP_RemovedFunctionParametersSniff in /opt/local/lib/php/PHP/CodeSniffer/Standards/Php53to54/Sniffs/PHP/RemovedFunctionParametersSniff.php on line 129

Call Stack:
    0.0002     233808   1. {main}() /opt/local/bin/phpcs:0
    0.0064    1162936   2. PHP_CodeSniffer_CLI->process() /opt/local/bin/phpcs:37
    0.0067    1171072   3. PHP_CodeSniffer->process() /opt/local/lib/php/PHP/CodeSniffer/CLI.php:579
    0.0068    1172968   4. PHP_CodeSniffer->setTokenListeners() /opt/local/lib/php/PHP/CodeSniffer.php:460

Any idea what I am doing wrong?

Regards,
Massi.

**Comment by goatherd** [comment]
The class for Sniffs/PHP/PutenvTZSniff.php is misnamed. A pending pull-request (#90) should fix this.

**Comment by MassiAtZend** [comment]
Closing, not relevant anymore.
